<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; line-height: 1.6; padding: 40px; }
        h1 { text-align: center; font-size: 18px; margin-bottom: 30px; text-transform: uppercase; }
        h2 { font-size: 14px; border-bottom: 1px solid #333; padding-bottom: 5px; margin-top: 25px; }
        .section { margin-bottom: 20px; }
        .row { margin-bottom: 6px; }
        .label { font-weight: bold; display: inline-block; width: 150px; }
        .signature-area { margin-top: 50px; display: flex; justify-content: space-between; }
        .signature-box { width: 200px; }
        .signature-line { border-top: 1px solid #333; margin-top: 50px; padding-top: 5px; font-size: 11px; }
        .terms { margin-top: 30px; font-size: 11px; }
        .terms ol { padding-left: 20px; }
        .terms li { margin-bottom: 8px; }
        .footer { position: fixed; bottom: 20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #666; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        table th, table td { padding: 8px 10px; border: 1px solid #ddd; text-align: left; }
        table th { background: #f5f5f5; }
    </style>
</head>
<body>
    <h1>Residential Lease Agreement</h1>

    <div class="section">
        <h2>Parties</h2>
        <div class="row"><span class="label">Landlord:</span> RentalFlow Management</div>
        <div class="row"><span class="label">Tenant:</span> {{ $tenant ? $tenant->name : 'N/A' }}</div>
        <div class="row"><span class="label">Email:</span> {{ $tenant ? $tenant->email : 'N/A' }}</div>
        <div class="row"><span class="label">Phone:</span> {{ $tenant ? $tenant->phone : 'N/A' }}</div>
    </div>

    <div class="section">
        <h2>Property</h2>
        <div class="row"><span class="label">Property:</span> {{ $property->name }}</div>
        <div class="row"><span class="label">Address:</span> {{ $property->address }}, {{ $property->city }}, {{ $property->state }} {{ $property->zip_code }}</div>
        <div class="row"><span class="label">Type:</span> {{ ucfirst($property->type) }}</div>
        <div class="row"><span class="label">Bedrooms:</span> {{ $property->bedrooms }}</div>
        <div class="row"><span class="label">Bathrooms:</span> {{ $property->bathrooms }}</div>
    </div>

    <div class="section">
        <h2>Lease Terms</h2>
        <div class="row"><span class="label">Check-In:</span> {{ $booking->check_in->format('F d, Y') }}</div>
        <div class="row"><span class="label">Check-Out:</span> {{ $booking->check_out->format('F d, Y') }}</div>
        <div class="row"><span class="label">Monthly Rent:</span> ${{ number_format($property->monthly_rent / 100, 2) }}</div>
        <div class="row"><span class="label">Security Deposit:</span> ${{ number_format($property->monthly_rent / 100, 2) }}</div>
    </div>

    <div class="terms">
        <h2>Terms &amp; Conditions</h2>
        <ol>
            <li><strong>Payment:</strong> Rent is due on the first of each month. Late payments after the 5th incur a $50 late fee.</li>
            <li><strong>Use:</strong> The premises shall be used exclusively as a private residence for the Tenant and approved occupants.</li>
            <li><strong>Maintenance:</strong> Tenant shall promptly report any maintenance issues. The Landlord is responsible for all major repairs.</li>
            <li><strong>Alterations:</strong> Tenant shall not make any alterations or improvements without prior written consent.</li>
            <li><strong>Pets:</strong> No pets are allowed without prior written agreement and additional deposit.</li>
            <li><strong>Subleasing:</strong> Subleasing or assignment of this agreement is strictly prohibited.</li>
            <li><strong>Termination:</strong> Either party must provide 30 days written notice for early termination.</li>
            <li><strong>Inspection:</strong> Landlord reserves the right to inspect the premises with 24 hours notice.</li>
        </ol>
    </div>

    <div class="signature-area">
        <div class="signature-box">
            <div class="signature-line">Landlord Signature &amp; Date</div>
        </div>
        <div class="signature-box">
            <div class="signature-line">Tenant Signature &amp; Date</div>
        </div>
    </div>

    <div class="footer">
        Generated by RentalFlow on {{ now()->format('F d, Y') }} &mdash; Booking #{{ $booking->id }}
    </div>
</body>
</html>
